#!/usr/bin/env Rscript

options(error = function() {
  traceback(2)
  q(status = 1)
})

suppressPackageStartupMessages({
  library(glue)
  library(optparse)
  library(this.path)
  library(UpSetR)
  library(vcfR)
  library(Gfreq)
})

option_list <- list(
  make_option(c("--vcf", "-v"), type = "character", help = "Path to genotyping VCF"),
  make_option(c("--libs", "-l"), type = "character", default = NULL, help = "Path to library name correspondence file"),
  make_option(c("--out_dir", "-o"), type = "character", help = "Path to output directory")
)

opt <- parse_args(OptionParser(option_list = option_list))

maf_pipeline(
  genotyping_vcf_path = opt$vcf,
  lib_names_corresp_path = opt$libs,
  out_dir = opt$out_dir
)
